# Generated by Django 3.0.3 on 2020-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='close',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='volume',
            new_name='percentChange',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='open',
            new_name='price',
        ),
    ]
