# Generated by Django 3.0.3 on 2020-03-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200301_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='percentChange',
            field=models.FloatField(),
        ),
    ]
