# Generated by Django 3.0.3 on 2020-03-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200301_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Currency',
        ),
    ]
