# Generated by Django 3.0.3 on 2020-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200309_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('percentChange', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
