# Generated by Django 3.0.3 on 2020-03-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200310_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
