# Generated by Django 3.0.3 on 2020-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200310_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='ticker',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='indice',
            name='ticker',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=30),
        ),
    ]
