# Generated by Django 3.0.3 on 2020-03-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200311_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='ticker',
            new_name='name',
        ),
    ]
