# Generated by Django 3.0.3 on 2020-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200311_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='names',
            new_name='name',
        ),
    ]
