# Generated by Django 3.0.3 on 2020-03-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200312_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indice',
            old_name='ticker',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='name',
        ),
    ]
