# Generated by Django 3.0.3 on 2020-03-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200314_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('date', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('adjClose', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
