# Generated by Django 3.0.3 on 2020-03-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_historicaldata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalData',
            new_name='MSFTHistorical',
        ),
    ]
