# Generated by Django 3.0.3 on 2020-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200315_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='change',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='percentChange',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='indice',
            name='change',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='indice',
            name='percentChange',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='indice',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
