# Generated by Django 3.0.3 on 2020-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200506_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='change',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='percentChange',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indice',
            name='change',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indice',
            name='percentChange',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indice',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
